version: '3.8'

services:
  app:
    build: .
    container_name: petbook-server
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-3010}
      - MONGO_URI=${MONGO_URI:-mongodb://mongo:27017/bd_petbook}
      - JWT_SECRET=${JWT_SECRET}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    depends_on:
      - mongo
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo:latest
    container_name: petbook-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: